  case AValue of
  stAdder:
  begin
    TrailLPoint[0] := GetTrailVector3(1, 3,4,5);
    TrailRPoint[0] := GetTrailVector3(1, 0,1,2);
    TrailLPoint[1] := GetTrailVector3(1, 0,1,2);
    TrailRPoint[1] := GetTrailVector3(1, 9,10,11);
    TrailLPoint[2] := GetTrailVector3(1, 9,10,11);
    TrailRPoint[2] := GetTrailVector3(1, 6,7,8);
    TrailLPoint[3] := GetTrailVector3(1, 6,7,8);
    TrailRPoint[3] := GetTrailVector3(1, 3,4,5);
    TrailColor := ColorCreate(96, 32, 32, 255);
  end;

  stAnaconda:
  begin
    TrailLPoint[0] := GetTrailVector3(1, 3,4,5);
    TrailRPoint[0] := GetTrailVector3(1, 0,1,2);
    TrailLPoint[1] := GetTrailVector3(1, 0,1,2);
    TrailRPoint[1] := GetTrailVector3(1, 6,7,8);
    TrailLPoint[2] := GetTrailVector3(1, 6,7,8);
    TrailRPoint[2] := GetTrailVector3(1, 3,4,5);
    TrailColor := ColorCreate(112, 48, 48, 255);
  end;

  stAspMk2:
  begin
    TrailLPoint[0] := GetTrailVector3(1, 3,4,5);
    TrailRPoint[0] := GetTrailVector3(1, 0,1,2);
    TrailLPoint[1] := GetTrailVector3(1, 0,1,2);
    TrailRPoint[1] := GetTrailVector3(1, 6,7,8);
    TrailLPoint[2] := GetTrailVector3(1, 6,7,8);
    TrailRPoint[2] := GetTrailVector3(1, 3,4,5);
    TrailColor := ColorCreate(32, 96, 96, 255);
  end;

  stBoa:
  begin
    TrailLPoint[0] := GetTrailVector3(1, 3,4,5);
    TrailRPoint[0] := GetTrailVector3(1, 0,1,2);
    TrailLPoint[1] := GetTrailVector3(1, 0,1,2);
    TrailRPoint[1] := GetTrailVector3(1, 6,7,8);
    TrailLPoint[2] := GetTrailVector3(1, 6,7,8);
    TrailRPoint[2] := GetTrailVector3(1, 3,4,5);
    TrailColor := ColorCreate(96, 159, 159, 255);
  end;

  stBoaCuiser:
  begin
    TrailLPoint[0] := GetTrailVector3(1, 3,4,5);
    TrailRPoint[0] := GetTrailVector3(1, 0,1,2);
    TrailLPoint[1] := GetTrailVector3(1, 0,1,2);
    TrailRPoint[1] := GetTrailVector3(1, 6,7,8);
    TrailLPoint[2] := GetTrailVector3(1, 6,7,8);
    TrailRPoint[2] := GetTrailVector3(1, 3,4,5);
    TrailColor := ColorCreate(32, 223, 159, 255);
  end;

  stCobraMk1:
   begin
     TrailLPoint[0] := GetTrailVector3(1, 3,4,5);
     TrailRPoint[0] := GetTrailVector3(1, 0,1,2);
     TrailLPoint[1] := GetTrailVector3(1, 0,1,2);
     TrailRPoint[1] := GetTrailVector3(1, 6,7,8);
     TrailLPoint[2] := GetTrailVector3(1, 6,7,8);
     TrailRPoint[2] := GetTrailVector3(1, 3,4,5);
     TrailLPoint[3] := GetTrailVector3(2, 3,4,5);
     TrailRPoint[3] := GetTrailVector3(2, 0,1,2);
     TrailLPoint[4] := GetTrailVector3(2, 0,1,2);
     TrailRPoint[4] := GetTrailVector3(2, 6,7,8);
     TrailLPoint[5] := GetTrailVector3(2, 6,7,8);
     TrailRPoint[5] := GetTrailVector3(2, 3,4,5);
     TrailColor := ColorCreate(32, 159, 223, 255);
   end;

  stCobraMk3:
   begin
     TrailLPoint[3] := GetTrailVector3(2, 9,10,11);
     TrailRPoint[3] := GetTrailVector3(2, 0,1,2);
     TrailLPoint[4] := GetTrailVector3(2, 0,1,2);
     TrailRPoint[4] := GetTrailVector3(2, 24,25,26);
     TrailLPoint[5] := GetTrailVector3(2, 24,25,26);
     TrailRPoint[5] := GetTrailVector3(2, 18,19,20);
     TrailLPoint[6] := GetTrailVector3(2, 18,19,20);
     TrailRPoint[6] := GetTrailVector3(2, 9,10,11);
     TrailLPoint[7] := GetTrailVector3(3, 9,10,11);
     TrailRPoint[7] := GetTrailVector3(3, 21,22,23);
     TrailLPoint[8] := GetTrailVector3(3, 21,22,23);
     TrailRPoint[8] := GetTrailVector3(3, 18,19,20);
     TrailLPoint[9] := GetTrailVector3(3, 18,19,20);
     TrailRPoint[9] := GetTrailVector3(3, 6,7,8);
     TrailLPoint[10] := GetTrailVector3(3, 6,7,8);
     TrailRPoint[10] := GetTrailVector3(3, 9,10,11);
     TrailColor := ColorCreate(96, 32, 223, 255);
   end;

  stFerDelance:
  begin
    TrailLPoint[0] := GetTrailVector3(1, 0,1,2);
    TrailRPoint[0] := GetTrailVector3(1, 3,4,5);
    TrailLPoint[1] := GetTrailVector3(1, 3,4,5);
    TrailRPoint[1] := GetTrailVector3(1, 6,7,8);
    TrailLPoint[2] := GetTrailVector3(1, 6,7,8);
    TrailRPoint[2] := GetTrailVector3(1, 9,10,11);
    TrailLPoint[3] := GetTrailVector3(1, 9,10,11);
    TrailRPoint[3] := GetTrailVector3(1, 0,1,2);
    TrailColor := ColorCreate(96, 32, 32, 255);
  end;

  stGecko:
  begin
    TrailLPoint[0] := GetTrailVector3(1, 0,1,2);
    TrailRPoint[0] := GetTrailVector3(1, 3,4,5);
    TrailLPoint[1] := GetTrailVector3(1, 3,4,5);
    TrailRPoint[1] := GetTrailVector3(1, 6,7,8);
    TrailLPoint[2] := GetTrailVector3(1, 6,7,8);
    TrailRPoint[2] := GetTrailVector3(1, 9,10,11);
    TrailLPoint[3] := GetTrailVector3(1, 9,10,11);
    TrailRPoint[3] := GetTrailVector3(1, 0,1,2);
    TrailColor := ColorCreate(112, 48, 48, 255);
  end;

  stKrait:
  begin
    TrailLPoint[0] := GetTrailVector3(1, 0,1,2);
    TrailRPoint[0] := GetTrailVector3(1, 3,4,5);
    TrailLPoint[1] := GetTrailVector3(1, 3,4,5);
    TrailRPoint[1] := GetTrailVector3(1, 6,7,8);
    TrailLPoint[2] := GetTrailVector3(1, 6,7,8);
    TrailRPoint[2] := GetTrailVector3(1, 0,1,2);
    TrailLPoint[3] := GetTrailVector3(2, 0,1,2);
    TrailRPoint[3] := GetTrailVector3(2, 3,4,5);
    TrailLPoint[4] := GetTrailVector3(2, 3,4,5);
    TrailRPoint[4] := GetTrailVector3(2, 6,7,8);
    TrailLPoint[5] := GetTrailVector3(2, 6,7,8);
    TrailRPoint[5] := GetTrailVector3(2, 0,1,2);
    TrailColor := ColorCreate(16, 80, 207, 255);
  end;

  stMamba:
  begin
    TrailLPoint[0] := GetTrailVector3(2, 0,1,2);
    TrailRPoint[0] := GetTrailVector3(2, 6,7,8);
    TrailLPoint[1] := GetTrailVector3(2, 6,7,8);
    TrailRPoint[1] := GetTrailVector3(2, 9,10,11);
    TrailLPoint[2] := GetTrailVector3(2, 9,10,11);
    TrailRPoint[2] := GetTrailVector3(2, 3,4,5);
    TrailLPoint[3] := GetTrailVector3(2, 3,4,5);
    TrailRPoint[3] := GetTrailVector3(2, 0,1,2);
    TrailColor := ColorCreate(96, 32, 32, 255);
  end;

  stMoray:
  begin
    TrailLPoint[0] := GetTrailVector3(1, 0,1,2);
    TrailRPoint[0] := GetTrailVector3(1, 3,4,5);
    TrailLPoint[1] := GetTrailVector3(2, 0,1,2);
    TrailRPoint[1] := GetTrailVector3(2, 3,4,5);
    TrailColor := ColorCreate(223, 159, 32, 255);
  end;

  stPython:
  begin
    TrailLPoint[0] := GetTrailVector3(1, 0,1,2);
    TrailRPoint[0] := GetTrailVector3(1, 9,10,11);
    TrailLPoint[1] := GetTrailVector3(1, 9,10,11);
    TrailRPoint[1] := GetTrailVector3(1, 6,7,8);
    TrailLPoint[2] := GetTrailVector3(1, 6,7,8);
    TrailRPoint[2] := GetTrailVector3(1, 3,4,5);
    TrailLPoint[3] := GetTrailVector3(1, 3,4,5);
    TrailRPoint[3] := GetTrailVector3(1, 0,1,2);
    TrailColor := ColorCreate(159, 159, 159, 255);
  end;

  stShuttle:
  begin
    TrailLPoint[0] := GetTrailVector3(1, 0,1,2);
    TrailRPoint[0] := GetTrailVector3(1, 6,7,8);
    TrailLPoint[1] := GetTrailVector3(1, 6,7,8);
    TrailRPoint[1] := GetTrailVector3(1, 3,4,5);
    TrailLPoint[2] := GetTrailVector3(1, 3,4,5);
    TrailRPoint[2] := GetTrailVector3(1, 0,1,2);
    TrailLPoint[3] := GetTrailVector3(2, 0,1,2);
    TrailRPoint[3] := GetTrailVector3(2, 6,7,8);
    TrailLPoint[4] := GetTrailVector3(2, 6,7,8);
    TrailRPoint[4] := GetTrailVector3(2, 3,4,5);
    TrailLPoint[5] := GetTrailVector3(2, 3,4,5);
    TrailRPoint[5] := GetTrailVector3(2, 0,1,2);
    TrailColor := ColorCreate(223, 96, 159, 255);
  end;

  stSidewinder:
  begin
    TrailLPoint[0] := GetTrailVector3(1, 3,4,5);
    TrailRPoint[0] := GetTrailVector3(1, 0,1,2);
    TrailLPoint[1] := GetTrailVector3(1, 0,1,2);
    TrailRPoint[1] := GetTrailVector3(1, 6,7,8);
    TrailLPoint[2] := GetTrailVector3(1, 6,7,8);
    TrailRPoint[2] := GetTrailVector3(1, 9,10,11);
    TrailLPoint[3] := GetTrailVector3(1, 9,10,11);
    TrailRPoint[3] := GetTrailVector3(1, 3,4,5);
    TrailColor := ColorCreate(147, 195, 235, 255);
  end;

  stTransporter:
  begin
    TrailLPoint[0] := GetTrailVector3(1, 3,4,5);
    TrailRPoint[0] := GetTrailVector3(1, 0,1,2);
    TrailLPoint[1] := GetTrailVector3(1, 0,1,2);
    TrailRPoint[1] := GetTrailVector3(1, 6,7,8);
    TrailLPoint[2] := GetTrailVector3(1, 6,7,8);
    TrailRPoint[2] := GetTrailVector3(1, 9,10,11);
    TrailLPoint[3] := GetTrailVector3(1, 9,10,11);
    TrailRPoint[3] := GetTrailVector3(1, 3,4,5);
    TrailColor := ColorCreate(96, 159, 159, 255);
  end;

  stViperPatrol:
  begin
    TrailLPoint[0] := GetTrailVector3(1, 3,4,5);
    TrailRPoint[0] := GetTrailVector3(1, 0,1,2);
    TrailLPoint[1] := GetTrailVector3(1, 0,1,2);
    TrailRPoint[1] := GetTrailVector3(1, 6,7,8);
    TrailLPoint[2] := GetTrailVector3(1, 6,7,8);
    TrailRPoint[2] := GetTrailVector3(1, 3,4,5);
    TrailLPoint[3] := GetTrailVector3(2, 3,4,5);
    TrailRPoint[3] := GetTrailVector3(2, 0,1,2);
    TrailLPoint[4] := GetTrailVector3(2, 0,1,2);
    TrailRPoint[4] := GetTrailVector3(2, 6,7,8);
    TrailLPoint[5] := GetTrailVector3(2, 6,7,8);
    TrailRPoint[5] := GetTrailVector3(2, 3,4,5);
    TrailColor := ColorCreate(32, 32, 96, 255);
  end;

  stViperInspector:
  begin
    TrailLPoint[0] := GetTrailVector3(1, 3,4,5);
    TrailRPoint[0] := GetTrailVector3(1, 0,1,2);
    TrailLPoint[1] := GetTrailVector3(1, 0,1,2);
    TrailRPoint[1] := GetTrailVector3(1, 6,7,8);
    TrailLPoint[2] := GetTrailVector3(1, 6,7,8);
    TrailRPoint[2] := GetTrailVector3(1, 3,4,5);
    TrailLPoint[3] := GetTrailVector3(2, 3,4,5);
    TrailRPoint[3] := GetTrailVector3(2, 0,1,2);
    TrailLPoint[4] := GetTrailVector3(2, 0,1,2);
    TrailRPoint[4] := GetTrailVector3(2, 6,7,8);
    TrailLPoint[5] := GetTrailVector3(2, 6,7,8);
    TrailRPoint[5] := GetTrailVector3(2, 3,4,5);
    TrailColor := ColorCreate(96, 32, 32, 255);
  end;

  stWorm:
  begin
   TrailLPoint[0] := GetTrailVector3(1, 0,1,2);
   TrailRPoint[0] := GetTrailVector3(1, 15,16,17);
   TrailLPoint[1] := GetTrailVector3(1, 15,16,17);
   TrailRPoint[1] := GetTrailVector3(1, 9,10,11);
   TrailLPoint[2] := GetTrailVector3(1, 9,10,11);
   TrailRPoint[2] := GetTrailVector3(1, 6,7,8);
   TrailLPoint[3] := GetTrailVector3(1, 6,7,8);
   TrailRPoint[3] := GetTrailVector3(1, 0,1,2);
   TrailColor := ColorCreate(223, 159, 159, 255);
  end;

  end;
